server:
  port: 5000

spring:
  profiles:
    active:  local #prod


  mail:
    host: smtp.gmail.com
    port: 587
    username: finalproject2danit@gmail.com # логин от учётки
    password: doskjmyncxzhdvsn # специальный пароль для приложения
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender: # отправитель письма (его почта и имя)
      email: test@gmail.com
      text: no-reply

# local profile
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:twitter
    username: sa
    password: sa
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred #default

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC

# prod profile
---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update #create-drop # update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://db-final-project-2.cx0wpt1wnne4.us-east-1.rds.amazonaws.com:5432/twitter
    username: postgres
    password: postgres
    initialization-mode: always # never

