server:
  port: 9000
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:homework
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2