MAIN_EMAIL:
MAIN_EMAIL_PASSWORD:
DB_URL:
DB_USER:
DB_PASSWORD:
server:
  port: 5000

spring:
  profiles:
    active: prod #local  # prod


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIN_EMAIL} # логин от учётки
    password: ${MAIN_EMAIL_PASSWORD} # специальный пароль для приложения
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender: # отправитель письма (его почта и имя)
      email: test@gmail.com
#      text: no-reply

myapp:
  baseUrl: http://twitterdemo.us-east-1.elasticbeanstalk.com

# local profile
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:twitter
    username: sa
    password: sa
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred #default

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC

# prod profile
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred #default
  jpa:
    hibernate:
      ddl-auto: update #update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC
  thymeleaf:
    enabled: true