server:
  port: 5000

spring:
  profiles:
    active: prod #local  # prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: finalproject2danit@gmail.com # логин от учётки
    password: doskjmyncxzhdvsn # специальный пароль для приложения
    test-connection: true # проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender: # отправитель письма (его почта и имя)
      email: test@gmail.com
#      text: no-reply
jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMdd_fAkl-nJL4EVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 360
  issuer: pervuy
# local profile
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:twitter
    username: sa
    password: sa
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred #default

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC

# prod profile
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db-final-project-2.cx0wpt1wnne4.us-east-1.rds.amazonaws.com:5432/twitter
    username: postgres
    password: postgres
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred #default
  jpa:
    hibernate:
      ddl-auto: update #create-drop #update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC
  thymeleaf:
    enabled: true
