language: java
jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "fp1-2"
    token: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FP1-2_final_project_2
  - mvn clean test jacoco:report coveralls:report
