language: java
jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "fp1-2"
    token: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean test jacoco:report coveralls:report
